# Generated by Django 3.0.6 on 2020-05-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='', max_length=200)),
                ('numero_compras', models.IntegerField(blank=True, default=0)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=7)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homely.Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('calificacion', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homely.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=7)),
                ('productos', models.ManyToManyField(to='Homely.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='reseñas',
            field=models.ManyToManyField(to='Homely.Reseña'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=7)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(to='Homely.Producto')),
                ('promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homely.Promocion')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Homely.Usuario')),
            ],
        ),
    ]
