# Generated by Django 3.0.6 on 2020-05-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='reseñas',
            field=models.ManyToManyField(blank=True, to='Homely.Reseña'),
        ),
    ]
