# Generated by Django 3.0.6 on 2020-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0002_auto_20200507_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='texto',
            field=models.TextField(default='', max_length=200),
        ),
    ]
