# Generated by Django 3.0.6 on 2020-05-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0003_reseña_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='reseñas',
            field=models.ManyToManyField(null=True, to='Homely.Reseña'),
        ),
    ]
