# Generated by Django 3.0.6 on 2020-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0007_auto_20200507_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='reseñas',
            field=models.ManyToManyField(blank=True, related_name='reseña', to='Homely.Reseña'),
        ),
    ]
