# Generated by Django 3.0.6 on 2020-05-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0008_auto_20200507_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
