# Generated by Django 3.0.6 on 2020-06-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0011_auto_20200612_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
