# Generated by Django 3.0.6 on 2020-06-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homely', '0012_auto_20200612_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homely.Promocion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_compras',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
